apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  - sealed-secrets.yaml
  - reflector.yaml
  - configs.yaml
  - longhorn.yaml
  - cert-manager.yaml
  - metallb.yaml
  - traefik.yaml
  - cloudnative-pg.yaml