apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-configs
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/cert-manager/configs
  prune: true
  timeout: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-install