apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-configs
  namespace: flux-system
spec:
  interval: 15m
  path: ./flux/infrastructure/base/metallb/configs
  prune: true
  timeout: 2m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: metallb-install