apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - letsencrypt-certification.namespace.yaml
  - letsencrypt-certification.cluster-issuer.yaml
  - letsencrypt-certification.certificate.yaml