apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-public-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - metallb-hetzner-ip-pools
  interfaces:
    - eth0
