apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-hetzner-ip-pools
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
    - 49.13.35.245/32
    - 116.203.13.34/32