apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - stalwart.namespace.yaml
  - stalwart.database.superuser.secret.yaml
  - stalwart.database.user.secret.yaml
  - stalwart.database.yaml
  - stalwart.secret.yaml
  - stalwart.config.yaml
  - stalwart.deployment.yaml
  - stalwart.service.yaml